[package]
name = "subtitle-workbench-desktop"
version = "0.1.0"
description = "Desktop shell for Subtitle Workbench"
edition = "2021"
publish = false
license = "PolyForm-Noncommercial-1.0.0"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"

[profile.release]
strip = true
lto = true
